import { z } from 'zod';
import { IAIProvider, ChatMessage, AIProviderResponse } from './ai.provider.interface';
import { ATLAS_SYSTEM_PROMPT } from '../prompts/system.prompt';

// Zod Schema to validate raw Google Gemini API response safely
const geminiResponseSchema = z.object({
  candidates: z.array(
    z.object({
      content: z.object({
        parts: z.array(
          z.object({
            text: z.string().optional().default(''),
          })
        ).min(1, 'Partes de conteúdo ausentes na resposta da Gemini'),
        role: z.string().optional(),
      }),
      finishReason: z.string().optional(),
    })
  ).min(1, 'Resposta da Gemini não contém candidatos válidos'),
});

// Zod Schema for safely parsing suggested action plans generated by the AI
const planStepSchema = z.object({
  stepNumber: z.number().int().positive(),
  title: z.string().min(1),
  description: z.string().optional(),
  timeWindow: z.string().optional(),
  howToExecute: z.string().optional(),
});

const suggestedPlanSchema = z.object({
  title: z.string().min(1),
  objective: z.string().min(1),
  reason: z.string().min(1),
  expectedResult: z.string().min(1),
  indicators: z.string().optional().default(''),
  risks: z.string().optional().default(''),
  contingencyPlan: z.string().optional().default(''),
  steps: z.array(planStepSchema).min(1),
});

export class GeminiProvider implements IAIProvider {
  private apiKey: string;
  private model: string;
  private baseUrl: string;
  private timeoutMs: number;

  constructor(
    apiKey: string,
    model = 'gemini-1.5-flash',
    baseUrl = 'https://generativelanguage.googleapis.com/v1beta',
    timeoutMs = 15000
  ) {
    this.apiKey = apiKey.trim();
    // If model is empty or set to an openai default like 'gpt-4o-mini', default to 'gemini-1.5-flash'
    const trimmedModel = model.trim();
    this.model = trimmedModel && !trimmedModel.startsWith('gpt-') ? trimmedModel : 'gemini-1.5-flash';
    
    // If baseUrl is set to an openai default, use the Gemini default
    const trimmedBaseUrl = baseUrl.replace(/\/+$/, '').trim();
    this.baseUrl = trimmedBaseUrl && !trimmedBaseUrl.includes('api.openai.com')
      ? trimmedBaseUrl
      : 'https://generativelanguage.googleapis.com/v1beta';
      
    this.timeoutMs = timeoutMs > 0 ? timeoutMs : 15000;
  }

  async chat(messages: ChatMessage[], contextString?: string): Promise<AIProviderResponse> {
    if (!this.apiKey) {
      throw new Error('[Gemini Provider] Chave de API (AI_API_KEY) não configurada.');
    }

    const fullSystemInstruction = `${ATLAS_SYSTEM_PROMPT}\n\n${contextString || ''}`.trim();

    // Map conversation messages to Gemini contents format
    // OpenAI 'user' -> Gemini 'user'; OpenAI 'assistant' -> Gemini 'model'
    const contents = messages
      .filter((m) => m.role === 'user' || m.role === 'assistant')
      .map((m) => ({
        role: m.role === 'assistant' ? 'model' : 'user',
        parts: [{ text: m.content }],
      }));

    // Ensure there is at least one content item
    if (contents.length === 0) {
      contents.push({
        role: 'user',
        parts: [{ text: 'Olá' }],
      });
    }

    const requestBody = {
      system_instruction: {
        parts: [{ text: fullSystemInstruction }],
      },
      contents,
      generationConfig: {
        temperature: 0.7,
      },
    };

    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), this.timeoutMs);

    const url = `${this.baseUrl}/models/${encodeURIComponent(this.model)}:generateContent`;

    let response: Response;
    try {
      response = await fetch(url, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'x-goog-api-key': this.apiKey,
        },
        body: JSON.stringify(requestBody),
        signal: controller.signal,
      });
    } catch (err: any) {
      if (err.name === 'AbortError' || controller.signal.aborted) {
        throw new Error(
          `[Gemini Timeout] A requisição excedeu o tempo limite configurado de ${this.timeoutMs / 1000}s.`
        );
      }
      throw new Error(
        `[Gemini Network Error] Falha na comunicação de rede com o endpoint (${err.message || 'Erro de conexão'}).`
      );
    } finally {
      clearTimeout(timeoutId);
    }

    // Handle HTTP status codes
    if (!response.ok) {
      const status = response.status;
      let safeErrorDetail = '';
      try {
        const errorJson = (await response.json()) as any;
        safeErrorDetail = errorJson?.error?.message || errorJson?.error?.status || '';
      } catch {
        safeErrorDetail = await response.text().catch(() => '');
      }

      if (status === 400 || status === 401 || status === 403) {
        throw new Error(
          `[Gemini Auth Error (${status})] Chave de API inválida, permissão negada ou requisição malformada. Detalhes: ${safeErrorDetail}`
        );
      }
      if (status === 429) {
        throw new Error(
          `[Gemini Rate Limit / Quota Error (429)] Limite de requisições ou cota de tokens excedida na Gemini API. Detalhes: ${safeErrorDetail}`
        );
      }
      if (status >= 500 && status < 600) {
        throw new Error(
          `[Gemini Server Error (${status})] Instabilidade temporária nos servidores da Google Gemini. Tente novamente mais tarde.`
        );
      }

      throw new Error(
        `[Gemini API Error (${status})] Requisição rejeitada pela API Gemini. Detalhes: ${safeErrorDetail}`
      );
    }

    // Safely parse JSON response
    let rawJson: unknown;
    try {
      rawJson = await response.json();
    } catch {
      throw new Error('[Gemini Response Error] A resposta retornada pela API não é um JSON válido.');
    }

    const parseResult = geminiResponseSchema.safeParse(rawJson);
    if (!parseResult.success) {
      throw new Error(
        `[Gemini Response Schema Error] Estrutura de resposta inesperada: ${parseResult.error.message}`
      );
    }

    const content = parseResult.data.candidates[0]?.content?.parts
      .map((p) => p.text)
      .join('\n')
      .trim() || 'Sem resposta gerada pelo modelo.';

    const suggestedPlan = this.extractSuggestedPlan(content);

    return {
      content,
      provider: 'gemini',
      model: this.model,
      suggestedPlan,
    };
  }

  /**
   * Safely attempts to extract and validate an action plan object from text or markdown code blocks.
   * If parsing or validation fails, it safely returns undefined without breaking the chat response.
   */
  private extractSuggestedPlan(text: string): AIProviderResponse['suggestedPlan'] {
    try {
      const jsonMatch = text.match(/```(?:json)?\s*(\{[\s\S]*?\})\s*```/);
      if (!jsonMatch) return undefined;

      const parsed = JSON.parse(jsonMatch[1]);
      const validated = suggestedPlanSchema.safeParse(parsed);
      if (validated.success) {
        return validated.data as AIProviderResponse['suggestedPlan'];
      }
    } catch {
      // Intentionally suppressed: safe fallback when response is regular markdown
    }
    return undefined;
  }
}
