import { z } from 'zod';
import { IAIProvider, ChatMessage, AIProviderResponse } from './ai.provider.interface';
import { ATLAS_SYSTEM_PROMPT } from '../prompts/system.prompt';

// Zod Schema to validate raw OpenAI API response safely
const openAIChatCompletionSchema = z.object({
  choices: z.array(
    z.object({
      message: z.object({
        content: z.string().nullable().optional(),
      }),
      finish_reason: z.string().nullable().optional(),
    })
  ).min(1, 'Resposta da OpenAI não contém opções (choices) válidas'),
});

// Zod Schema for safely parsing suggested action plans generated by the AI
const planStepSchema = z.object({
  stepNumber: z.number().int().positive(),
  title: z.string().min(1),
  description: z.string().optional(),
  timeWindow: z.string().optional(),
  howToExecute: z.string().optional(),
});

const suggestedPlanSchema = z.object({
  title: z.string().min(1),
  objective: z.string().min(1),
  reason: z.string().min(1),
  expectedResult: z.string().min(1),
  indicators: z.string().optional().default(''),
  risks: z.string().optional().default(''),
  contingencyPlan: z.string().optional().default(''),
  steps: z.array(planStepSchema).min(1),
});

export class OpenAIProvider implements IAIProvider {
  private apiKey: string;
  private model: string;
  private baseUrl: string;
  private timeoutMs: number;

  constructor(
    apiKey: string,
    model = 'gpt-4o-mini',
    baseUrl = 'https://api.openai.com/v1',
    timeoutMs = 15000
  ) {
    this.apiKey = apiKey.trim();
    this.model = model.trim() || 'gpt-4o-mini';
    this.baseUrl = baseUrl.replace(/\/+$/, '');
    this.timeoutMs = timeoutMs > 0 ? timeoutMs : 15000;
  }

  async chat(messages: ChatMessage[], contextString?: string): Promise<AIProviderResponse> {
    if (!this.apiKey) {
      throw new Error('[OpenAI Provider] Chave de API (AI_API_KEY) não configurada.');
    }

    const formattedMessages: ChatMessage[] = [
      {
        role: 'system',
        content: `${ATLAS_SYSTEM_PROMPT}\n\n${contextString || ''}`,
      },
      ...messages,
    ];

    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), this.timeoutMs);

    let response: Response;
    try {
      response = await fetch(`${this.baseUrl}/chat/completions`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${this.apiKey}`,
        },
        body: JSON.stringify({
          model: this.model,
          messages: formattedMessages,
          temperature: 0.7,
        }),
        signal: controller.signal,
      });
    } catch (err: any) {
      if (err.name === 'AbortError' || controller.signal.aborted) {
        throw new Error(
          `[OpenAI Timeout] A requisição excedeu o tempo limite configurado de ${this.timeoutMs / 1000}s.`
        );
      }
      throw new Error(
        `[OpenAI Network Error] Falha na comunicação de rede com o endpoint (${err.message || 'Erro de conexão'}).`
      );
    } finally {
      clearTimeout(timeoutId);
    }

    // Handle HTTP status codes appropriately
    if (!response.ok) {
      const status = response.status;
      let safeErrorDetail = '';
      try {
        const errorJson = (await response.json()) as any;
        safeErrorDetail = errorJson?.error?.message || '';
      } catch {
        safeErrorDetail = await response.text().catch(() => '');
      }

      if (status === 401) {
        throw new Error(
          `[OpenAI Auth Error (401)] Chave de API inválida, revogada ou não autorizada. Detalhes: ${safeErrorDetail}`
        );
      }
      if (status === 429) {
        throw new Error(
          `[OpenAI Rate Limit / Quota Error (429)] Limite de requisições ou cota de tokens excedida. Detalhes: ${safeErrorDetail}`
        );
      }
      if (status >= 500 && status < 600) {
        throw new Error(
          `[OpenAI Server Error (${status})] Instabilidade temporária nos servidores da OpenAI. Tente novamente mais tarde.`
        );
      }

      throw new Error(
        `[OpenAI API Error (${status})] Requisição rejeitada pela API. Detalhes: ${safeErrorDetail}`
      );
    }

    // Safely parse JSON response without blind trust
    let rawJson: unknown;
    try {
      rawJson = await response.json();
    } catch {
      throw new Error('[OpenAI Response Error] A resposta retornada pela API não é um JSON válido.');
    }

    const parseResult = openAIChatCompletionSchema.safeParse(rawJson);
    if (!parseResult.success) {
      throw new Error(
        `[OpenAI Response Schema Error] Estrutura de resposta inesperada: ${parseResult.error.message}`
      );
    }

    const content = parseResult.data.choices[0]?.message?.content || 'Sem resposta gerada pelo modelo.';

    // Safely attempt to detect and validate any structured plan JSON in the response
    const suggestedPlan = this.extractSuggestedPlan(content);

    return {
      content,
      provider: 'openai',
      model: this.model,
      suggestedPlan,
    };
  }

  /**
   * Safely attempts to extract and validate an action plan object from text or markdown code blocks.
   * If parsing or validation fails, it safely returns undefined without breaking the chat response.
   */
  private extractSuggestedPlan(text: string): AIProviderResponse['suggestedPlan'] {
    try {
      const jsonMatch = text.match(/```(?:json)?\s*(\{[\s\S]*?\})\s*```/);
      if (!jsonMatch) return undefined;

      const parsed = JSON.parse(jsonMatch[1]);
      const validated = suggestedPlanSchema.safeParse(parsed);
      if (validated.success) {
        return validated.data as AIProviderResponse['suggestedPlan'];
      }
    } catch {
      // Intentionally suppressed: safe fallback when response is regular markdown
    }
    return undefined;
  }
}
